name: Setup Node.js Environment for Copilot

steps:
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
          node-version-file: package.json
          cache: "npm"

    - name: Install dependencies
      run: npm install
