configDependencies:
    "@obusk/pnpm-plugin-defaults": 0.2.0+sha512-3oufTLQAL1SDdQ9iA5hLRnZjnBnU9uIEOBcwCKRtS+F6NyJphTq6RMIpaZgostZjQRHUaNbGSg6B2gn91drCSQ==

minimumReleaseAgeExclude:
    - next
    - "@next/*"
    - eslint-config-next
    - "@obusk/eslint-config-next"
    - ts-api-utils@2.4.0

allowBuilds:
    sharp: true
    simple-git-hooks@2.13.1: true
    unrs-resolver: true

overrides:
    "@types/react": 19.2.10
    "@types/react-dom": 19.2.3

trustPolicyExclude:
    - eslint-import-resolver-typescript@3.10.1
    - semver@6.3.1
    - tailwindcss@3.4.18
