configDependencies:
    "@obusk/pnpm-plugin-defaults": 0.2.0+sha512-3oufTLQAL1SDdQ9iA5hLRnZjnBnU9uIEOBcwCKRtS+F6NyJphTq6RMIpaZgostZjQRHUaNbGSg6B2gn91drCSQ==

hoistPattern:
    - "@babel/runtime"

minimumReleaseAgeExclude:
    - next
    - "@next/*"
    - eslint-config-next
    - "@obusk/eslint-config-next"

onlyBuiltDependencies:
    - sharp@0.34.5
    - simple-git-hooks@2.13.1
    - unrs-resolver@1.11.1

trustPolicyExclude:
    - eslint-import-resolver-typescript@3.10.1
    - semver@6.3.1
    - tailwindcss@3.4.18
