configDependencies:
    "@obusk/pnpm-plugin-defaults": 0.1.0+sha512-vsCchpE+K6g67YdDYYBCVQQFpfVFuVV423CCBbUEBm7FmWg/MI0Keuhkb6bjWpWaITE1PMSmcsrXbHv9FPFloA==

hoistPattern:
    - "@babel/runtime"

minimumReleaseAgeExclude:
    - next
    - "@next/*"
    - eslint-config-next
    - "@obusk/eslint-config-next"

onlyBuiltDependencies:
    - sharp@0.34.4
    - simple-git-hooks@2.13.1
    - unrs-resolver@1.11.1
