configDependencies:
    "@obusk/pnpm-plugin-defaults": 0.5.6

minimumReleaseAgeExclude:
    - next
    - "@next/*"
    - eslint-config-next
    - "@obusk/eslint-config-next"
    - ts-api-utils@2.4.0

allowBuilds:
    sharp: true
    simple-git-hooks@2.13.1: true
    unrs-resolver: true

overrides:
    "@types/react": 19.2.14
    "@types/react-dom": 19.2.3

trustPolicyExclude:
    - eslint-import-resolver-typescript@3.10.1
    - semver@6.3.1
    - tailwind-merge@2.6.1
